src/Entity/Salle.php
<?php

namespace App\Entity;

use App\Repository\SalleRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=SalleRepository::class)
 */
class Salle
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer")
     */
    private $num_salle;

    /**
     * @ORM\OneToMany(targetEntity=Seance::class, mappedBy="salle", orphanRemoval=true)
     */
    private $seance;

    public function __construct()
    {
        $this->seance = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNumSalle(): ?int
    {
        return $this->num_salle;
    }

    public function setNumSalle(int $num_salle): self
    {
        $this->num_salle = $num_salle;

        return $this;
    }

    /**
     * @return Collection<int, Seance>
     */
    public function getSeance(): Collection
    {
        return $this->seance;
    }

    public function addSeance(Seance $seance): self
    {
        if (!$this->seance->contains($seance)) {
            $this->seance[] = $seance;
            $seance->setSalle($this);
        }

        return $this;
    }

    public function removeSeance(Seance $seance): self
    {
        if ($this->seance->removeElement($seance)) {
            // set the owning side to null (unless already changed)
            if ($seance->getSalle() === $this) {
                $seance->setSalle(null);
            }
        }

        return $this;
    }
}

src/Form/SalleType.php
<?php

namespace App\Form;

use App\Entity\Salle;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class SalleType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('num_salle', TextType::class, [
                'label' => 'Numéro de salle',])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Salle::class,
        ]);
    }
}

src/Controller/SalleController.php
<?php

namespace App\Controller;

use App\Entity\Salle;
use App\Form\SalleType;
use App\Repository\SalleRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/salle")
 */
class SalleController extends AbstractController
{
    /**
     * @Route("/", name="salle_index", methods={"GET"})
     */
    public function index(SalleRepository $salleRepository): Response
    {
        return $this->render('salle/index.html.twig', [
            'salles' => $salleRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="salle_new", methods={"GET", "POST"})
     */
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $salle = new Salle();
        $form = $this->createForm(SalleType::class, $salle);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($salle);
            $entityManager->flush();

            return $this->redirectToRoute('salle_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('salle/new.html.twig', [
            'salle' => $salle,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="salle_show", methods={"GET"})
     */
    public function show(Salle $salle): Response
    {
        return $this->render('salle/show.html.twig', [
            'salle' => $salle,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="salle_edit", methods={"GET", "POST"})
     */
    public function edit(Request $request, Salle $salle, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(SalleType::class, $salle);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('salle_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('salle/edit.html.twig', [
            'salle' => $salle,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="salle_delete", methods={"POST"})
     */
    public function delete(Request $request, Salle $salle, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$salle->getId(), $request->request->get('_token'))) {
            $entityManager->remove($salle);
            $entityManager->flush();
        }

        return $this->redirectToRoute('salle_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/salle/_delete_form.html.twig
<form method="post" action="{{ path('salle_delete', {'id': salle.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ salle.id) }}">
    <button class="btn"><i class="fa-solid fa-trash-can"></i></button>
</form>

templates/salle/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Créer') }}</button>
{{ form_end(form) }}

templates/salle/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modification d'une salle{% endblock %}

{% block body %}

    <div class="film-add">
        <div class="film-add-container">

            <div class="film-add-title">
                <h2>Modification d'une salle</h2>
            </div>

            {{ include('salle/_form.html.twig', {'button_label': 'Update'}) }}

            <a href="{{ path('salle_index') }}">Revenir à la liste</a>

            <div class="seance-btn">
                {{ include('salle/_delete_form.html.twig') }}
            </div>

        </div>
    </div>

{% endblock %}

templates/salle/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Salles disponibles{% endblock %}

{% block body %}
    <div class="seance-and-salle-list">
        <div class="seance-and-salle-list-container">

            <h2>Salles disponibles</h2>

            <table class="table">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Numéro de salle</th>
                        <th>actions</th>
                    </tr>
                </thead>
                <tbody>
                {% for salle in salles %}
                    <tr>
                        <td class="id">{{ salle.id }}</td>
                        <td>{{ salle.numSalle }}</td>
                        <td class="actions">
                            <a href="{{ path('salle_show', {'id': salle.id}) }}">show</a>
                            <a href="{{ path('salle_edit', {'id': salle.id}) }}">edit</a>
                        </td>
                    </tr>
                {% else %}
                    <tr>
                        <td colspan="3">Pas de salle</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>

            <div class="btn-new">
                <a href="{{ path('salle_new') }}">Create new</a>
            </div>

        </div>
    </div>

{% endblock %}

templates/salle/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nouvelle salle{% endblock %}

{% block body %}

    <div class="film-add">
        <div class="film-add-container">

            <div class="film-add-title">
                <h2>Nouvelle salle</h2>
            </div>

            {{ include('salle/_form.html.twig') }}

            <a href="{{ path('salle_index') }}">Revenir à la liste</a>
        </div>
    </div>

{% endblock %}

templates/salle/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Salles{% endblock %}

{% block body %}

<div class="image-fond-seance">

    <div class="seance-and-salle-list">
        <div class="seance-and-salle-list-container">

            <h2>Salles</h2>

            <table class="table">
                <tbody>
                    <tr>
                        <th>ID</th>
                        <td>{{ salle.id }}</td>
                    </tr>
                    <tr>
                        <th>Numéro de salle</th>
                        <td>{{ salle.numSalle }}</td>
                    </tr>
                </tbody>
            </table>

            <div class="btn-salle-show" >
                <a href="{{ path('salle_index') }}">Revenir à la liste</a>

                <a href="{{ path('salle_edit', {'id': salle.id}) }}">Modifier</a>

                {{ include('salle/_delete_form.html.twig') }}
            <div>

        </div>
    </div>
</div>
{% endblock %}